// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCB6fSxCySXOcFkR2yMzjofCuLp2IiLYE',
    appId: '1:897619785636:web:5b0852be3997d408737331',
    messagingSenderId: '897619785636',
    projectId: 'gameufcspaici',
    authDomain: 'gameufcspaici.firebaseapp.com',
    databaseURL: 'https://gameufcspaici-default-rtdb.firebaseio.com/',
    storageBucket: 'gameufcspaici.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArZOn96S-D_Dc5MQTEVVltQMJwiSL2Wmc',
    appId: '1:897619785636:android:a5f1d54ce37e98ea737331',
    messagingSenderId: '897619785636',
    projectId: 'gameufcspaici',
    storageBucket: 'gameufcspaici.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIHLUiBLRcCD2qqlvh3qEpR7qhjKNyf28',
    appId: '1:897619785636:ios:3a14dec7d0dee4c6737331',
    messagingSenderId: '897619785636',
    projectId: 'gameufcspaici',
    storageBucket: 'gameufcspaici.appspot.com',
    iosClientId:
        '897619785636-1con1vcpn9h7h1hp6angmlosjd24utar.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameici',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIHLUiBLRcCD2qqlvh3qEpR7qhjKNyf28',
    appId: '1:897619785636:ios:3a14dec7d0dee4c6737331',
    messagingSenderId: '897619785636',
    projectId: 'gameufcspaici',
    storageBucket: 'gameufcspaici.appspot.com',
    iosClientId:
        '897619785636-1con1vcpn9h7h1hp6angmlosjd24utar.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameici',
  );
}
